
local solarisEmoticons = {
    ["ayayaKMS"] = "ayayaKMS",
    ["AzorCool"] = "AzorCool",
    ["Bedge"] = "Bedge",
    ["blusherBucket"] = "blusherBucket",
	["BlushPJ"] = "BlushPJ",
    ["catDisgust"] = "catDisgust",
    [":clueless:"] = "CLUELESS",
    ["comfyBlushSip"] = "comfyBlushSip",
    ["Copium"] = "Copium",
    ["cozyFriends"] = "cozyFriends",
    ["DASSARA"] = "DASSARA",
    ["DinkDonk"] = "DinkDonk",
    ["DistortedWeird"] = "DistortedWeird",
    ["FeelsIonMan"] = "FeelsIonMan",
    ["happyAwesome"] = "happyAwesome",
    ["HappyPeepoFarmer"] = "HappyPeepoFarmer",
    ["LETSGO"] = "LETSGO",
    ["MAAAN"] = "MAAAN",
    ["monkaYikes"] = "monkaYikes",
    ["MONKS"] = "MONKS",
    ["NootLikeThis"] = "NootLikeThis",
    ["nyoo"] = "nyoo",
    ["peepoBabyShark"] = "peepoBabyShark",
    ["peepoBear"] = "peepoBear",
    ["peepoDrool"] = "peepoDrool",
    ["peepoFlower"] = "peepoFlower",
    ["peepoHappyFrog"] = "peepoHappyFrog",
    ["peepoHappyNuggie"] = "peepoHappyNuggie",
    ["peepoHug"] = "peepoHug",
    ["peepoMonke"] = "peepoMonke",
    ["peepoRecline"] = "peepoRecline",
    ["peepoShy"] = "peepoShy",
    ["peepoSmiles"] = "peepoSmiles",
	["peepoStrawberry"] ="peepoStrawberry",
    ["peepoSweat"] ="peepoSweat",
    ["peepoWhat"] ="peepoWhat",
    ["pepeComfy"] = "pepeComfy",
    ["pepeDepressed"] = "pepeDepressed",
    ["pepeEmu"] = "pepeEmu",
    ["pepeGrump"] = "pepeGrump",
    ["pepeJudge"] = "pepeJudge",
    ["pepeOld"] = "pepeOld",
    ["pepePhone"] = "pepePhone",
    ["pepeSmoke"] = "pepeSmoke",
    ["pepeW"] = "pepeW",
    ["PolarBear"] = "PolarBear",
    ["prayge"] = "prayge",
    ["sheepoHug"] = "sheepoHug",
    ["sheepoHugBerry"] = "sheepoHugBerry",
    ["smoge"] = "smoge",
    ["susge"] = "susge",
    ["thinkiong"] = "thinkiong",
    ["THYMINDE"] = "THYMINDE",
    ["typingHappy"] = "typingHappy",
    ["WannaFight"] = "WannaFight",
    ["Wokege"] = "Wokege",
    ["YEPSOCK"] = "YEPSOCK",

    -- Large Emotes
    ["ayayaKMSW"] = "ayayaKMSW",
    ["AYAYAW"] = "AYAYAW",
    ["FeelsIonManW"] = "FeelsIonManW",

    -- Wide Emotes
    ["WideAYAYA"] = "WideAYAYA",
    ["WideDistortedWeird"] = "WideDistortedWeird",

    -- Alternatives
    ["FUCKKINTARK"] = "comfyBlushSip",
    ["letsgo"] = "LETSGO",
    ["maan"] = "MAAAN",
    ["maaan"] = "MAAAN",
    ["MAAN"] = "MAAAN",
    ["NYOO"] = "nyoo",
}


local solarisPack = {
    ["ayayaKMS"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\ayayaKMS.tga:28:28",
    ["AzorCool"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\AzorCool.tga:28:28",
    ["Bedge"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\Bedge.tga:28:28",
    ["blusherBucket"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\blusherBucket.tga:28:28",
	["BlushPJ"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\BlushPJ.tga:28:28",
    ["catDisgust"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\catDisgust.tga:28:28",
    ["CLUELESS"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\CLUELESS.tga:28:28",
    ["comfyBlushSip"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\comfyBlushSip.tga:28:28",
    ["Copium"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\Copium.tga:28:28",
    ["cozyFriends"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\cozyFriends.tga:28:28",
    ["DASSARA"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\DASSARA.tga:28:28",
    ["DinkDonk"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\DinkDonk.tga:28:28",
    ["DistortedWeird"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\DistortedWeird.tga:28:28",
    ["FeelsIonMan"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\FeelsIonMan.tga:28:28",
    ["happyAwesome"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\happyAwesome.tga:28:28",
    ["HappyPeepoFarmer"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\HappyPeepoFarmer.tga:28:28",
    ["LETSGO"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\LETSGO.tga:28:28",
    ["MAAAN"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\MAAAN.tga:28:28",
    ["monkaYikes"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\monkaYikes.tga:28:28",
    ["MONKS"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\MONKS.tga:28:28",
    ["NootLikeThis"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\NootLikeThis.tga:28:28",
    ["nyoo"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\nyoo.tga:28:28",
    ["peepoBabyShark"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoBabyShark.tga:28:28",
    ["peepoBear"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoBear.tga:28:28",
    ["peepoDrool"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoDrool.tga:28:28",
    ["peepoFlower"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoFlower.tga:28:28",
    ["peepoHappyFrog"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoHappyFrog.tga:28:28",
    ["peepoHappyNuggie"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoHappyNuggie.tga:28:28",
    ["peepoHug"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoHug.tga:28:28",
    ["peepoMonke"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoMonke.tga:28:28",
    ["peepoRecline"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoRecline.tga:28:28",
    ["peepoShy"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoShy.tga:28:28",
    ["peepoSmiles"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoSmiles.tga:28:28",
	["peepoStrawberry"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoStrawberry.tga:28:28",
    ["peepoSweat"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoSweat.tga:28:28",
    ["peepoWhat"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\peepoWhat.tga:28:28",
    ["pepeComfy"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepeComfy.tga:28:28",
    ["pepeDepressed"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepeDepressed.tga:28:28",
    ["pepeEmu"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepeEmu.tga:28:28",
    ["pepeGrump"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepeGrump.tga:28:28",
    ["pepeJudge"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepeJudge.tga:28:28",
    ["pepeOld"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepeOld.tga:28:28",
    ["pepePhone"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepePhone.tga:28:28",
    ["pepeSmoke"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepeSmoke.tga:28:28",
    ["pepeW"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\pepeW.tga:28:28",
    ["PolarBear"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\PolarBear.tga:28:28",
    ["prayge"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\prayge.tga:28:28",
    ["sheepoHug"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\sheepoHug.tga:28:28",
    ["sheepoHugBerry"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\sheepoHugBerry.tga:28:28",
    ["smoge"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\smoge.tga:28:28",
    ["susge"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\susge.tga:28:28",
    ["thinkiong"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\thinkiong.tga:28:28",
    ["THYMINDE"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\THYMINDE.tga:28:28",
    ["typingHappy"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\typingHappy.tga:28:28",
    ["WannaFight"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\WannaFight.tga:28:28",
    ["Wokege"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\Wokege.tga:28:28",
    ["YEPSOCK"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\YEPSOCK.tga:28:28",

    -- Large Emotes
    ["ayayaKMSW"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\large\\ayayaKMSW.tga:LARGE",
    ["AYAYAW"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\large\\AYAYAW.tga:LARGE",
    ["FeelsIonManW"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\large\\FeelsIonManW.tga:LARGE",

    -- Wide Emotes
    ["WideAYAYA"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\wide\\WideAYAYA.tga:28:128",
    ["WideDistortedWeird"] = "Interface\\AddOns\\TwitchEmotes_Solaris\\emotes\\wide\\WideDistortedWeird.tga:28:128",
}

local function addEmotePacks()
    Emoticons_RegisterPack("TwitchEmotes_Solaris", solarisEmoticons, solarisPack)
end

addEmotePacks()